// Google Apps Script backend for Generic Fashion Survey v3.
// IMPORTANT: Google Apps Script project files should use .gs, so keep this as Code.gs.
const CONFIG={VERSION:"3.0",RESPONSE_SHEET:"Responses",PRODUCT_SHEET:"Products",MULTI_SHEET:"MultiSelect",METADATA_SHEET:"Metadata"};
const RESPONSE_HEADERS=["Response ID","Timestamp","Age Group","Occupation","Shopping City","Shop For","Shopping Frequency","Current Stores","Trip Spend","Shopping Channel","Store Expectations","Final Message","Contact","Source","Survey Version","Raw JSON"];
const PRODUCT_HEADERS=["Response ID","Timestamp","Product ID","Product","Price Preference"];
const MULTI_HEADERS=["Response ID","Timestamp","Question","Value"];
function doGet(){return ContentService.createTextOutput(JSON.stringify({status:"ok",service:"generic-fashion-survey",version:CONFIG.VERSION,timestamp:new Date().toISOString()})).setMimeType(ContentService.MimeType.JSON)}
function doPost(e){const payload=parse_(e),a=payload.answers||payload,ts=value_(payload.timestamp)||new Date().toISOString(),rid=value_(payload.responseId)||makeId_(ts),ss=SpreadsheetApp.getActiveSpreadsheet(),rs=sheet_(ss,CONFIG.RESPONSE_SHEET,RESPONSE_HEADERS),ps=sheet_(ss,CONFIG.PRODUCT_SHEET,PRODUCT_HEADERS),ms=sheet_(ss,CONFIG.MULTI_SHEET,MULTI_HEADERS),meta=sheet_(ss,CONFIG.METADATA_SHEET,["Key","Value"]);
rs.appendRow([rid,ts,value_(a.ageGroup),value_(a.occupation),value_(a.shoppingCity),join_(a.shopFor),value_(a.shoppingFrequency),join_(a.currentStores),value_(a.tripSpend),value_(a.shoppingChannel),join_(a.storeExpectations),value_(a.finalMessage),value_(a.contact),value_(payload.source),value_(payload.surveyVersion),JSON.stringify(payload)]);
(Array.isArray(payload.selectedProducts)?payload.selectedProducts:[]).forEach(p=>ps.appendRow([rid,ts,value_(p.id),value_(p.label),value_(p.price)]));
[["Shop For",a.shopFor],["Current Stores",a.currentStores],["Store Expectations",a.storeExpectations]].forEach(([q,v])=>{if(Array.isArray(v))v.forEach(x=>ms.appendRow([rid,ts,q,value_(x)]))});
meta.clearContents();meta.getRange(1,1,4,2).setValues([["Version",CONFIG.VERSION],["Last Response ID",rid],["Last Response Timestamp",ts],["Last Updated",new Date().toISOString()]]);
return ContentService.createTextOutput(JSON.stringify({status:"ok",responseId:rid,version:CONFIG.VERSION})).setMimeType(ContentService.MimeType.JSON)}
function parse_(e){try{return JSON.parse(e.postData.contents)}catch(x){return{}}}function sheet_(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0){s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1)}return s}function value_(v){return v==null?"":String(v)}function join_(v){return Array.isArray(v)?v.join(", "):value_(v)}function makeId_(ts){let d=new Date(ts),s="";for(let i=0;i<6;i++)s+="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)];return"GFS-"+Utilities.formatDate(d,Session.getScriptTimeZone(),"yyyyMMdd")+"-"+s}